[mod]
name = "Fair Freecam"
id = "freecam"
group = "net.xolt.freecam"
# Version can specify a semver pre-release, e.g. -alpha.1
version = "26.7.0"
authors = ["m1dLL3"]
license = "MIT"
homepage = "https://minecraftfreecam.github.io"
source = "https://github.com/MinecraftFreecam/Freecam"
issues = "https://github.com/MinecraftFreecam/Freecam/issues"
github_releases = "https://github.com/MinecraftFreecam/Freecam/releases"
curseforge = "https://www.curseforge.com/minecraft/mc-mods/free-cam"
modrinth = "https://modrinth.com/mod/fairfreecam"
crowdin = "https://crowdin.com/project/freecam"
curseforge_id = 557076
modrinth_id = "JI58LZI4"
