# See https://stonecutter.kikugie.dev/wiki/config/settings#data-driven-setup
"$schema" = "https://stonecutter.kikugie.dev/settings-schema/latest.json"

# The version used by "reset active project"
vcs = "26.2"

# Gradle projects to build for the corresponding Minecraft version.
[versions]
"26.2" = ["cloth-config", "common", "fabric"]
"26.1.2" = ["cloth-config", "common", "fabric"]
"1.21.11" = ["cloth-config", "common", "fabric"]
